apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebsite-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplewebsite
  template:
    metadata:
      labels:
        app: samplewebsite
    spec:
      containers:
      - name: samplewebsite
        image: adityakumar10mm/samplewebsite
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebsite-service
  namespace: app
spec:
  selector:
    app: samplewebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
